### ISSUE TITLE
it  cant  work suddenly  now ,what happened

### ISSUE THREAD

**Issue by leixiaokou** [Ayesh/InstagramDownload#11]
it  cant  work suddenly  now ,what happened?  the below is the exception in  last one catch  form demo, thanks for your help
i  use aws  ec2   ， on server can  ping  the website Instagram 
#0 /usr/local/var/www/beauty/vendor/ayesh/instagram-download/src/InstagramDownload.php(75): Ayesh\InstagramDownload\InstagramDownload->fetch('https://www.ins... ▶
#1 /usr/local/var/www/beauty/vendor/ayesh/instagram-download/src/InstagramDownload.php(57): Ayesh\InstagramDownload\InstagramDownload->process()\n
#2 /usr/local/var/www/beauty/app/Http/Services/RemoveWater/RemoveWater.php(84): Ayesh\InstagramDownload\InstagramDownload->getDownloadUrl()\n
#3 /usr/local/var/www/beauty/app/Http/Services/RemoveWater/RemoveWater.php(47): App\Http\Services\RemoveWater\RemoveWater->instagram('https://www.ins...')\n
#4 /usr/local/var/www/beauty/app/Http/Controllers/Api/RemoveWater/IndexController.php(25): App\Http\Services\RemoveWater\RemoveWater->run('https://www.ins...')\ ▶
#5 [internal function]: App\Http\Controllers\Api\RemoveWater\IndexController->index(Object(Illuminate\Http\Request))\n
#6 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)\n
#7 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Ar ▶
#8 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate ▶
#9 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()\n
#10 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()\n
#11 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(I ▶
#12 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Rou ▶
#13 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Objec ▶
#14 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#15 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\Routing\Pipeline->Illuminate\Routi ▶
#16 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object( ▶
#17 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#18 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Obje ▶
#19 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))\n
#20 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\ ▶
#21 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Reques ▶
#22 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http ▶
#23 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Htt ▶
#24 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{c ▶
#25 /usr/local/var/www/beauty/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\ ▶
#26 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Re ▶
#27 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#28 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illumin ▶
#29 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handl ▶
#30 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#31 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illumin ▶
#32 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handl ▶
#33 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#34 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illumina ▶
#35 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle ▶
#36 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#37 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->I ▶
#38 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode- ▶
#39 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#40 /usr/local/var/www/beauty/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illumin ▶
#41 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\R ▶
#42 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Obje ▶
#43 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Obje ▶
#44 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))\n
#45 /usr/local/var/www/beauty/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRout ▶
#46 /usr/local/var/www/beauty/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))\n
#47 /usr/local/var/www/beauty/server.php(21): require_once('/usr/local/var/...')\n
#48 {main}

**Comment by Ayesh** [comment]
Instagram no longer allows anonymous page views, so unless you authenticate yourself to Instagram and workaround the rate limits, this library is not functional anymore.
