### ISSUE TITLE
Not working - Returning 500 when using the API

### ISSUE THREAD

**Issue by shashifreeze** [Ayesh/InstagramDownload#13]
I have used composer to autoload class. But the API is not working. Please look into the issue.
Thanks in advance.

**Comment by peter279k** [comment]
Please provide the sample codes and I can help you to reproduce the issue.

Please  provide following things:

- Which branch (released version) you use.
- Sample codes.
- Steps to reproducing this issue you mention.

**Comment by shashifreeze** [comment]
This is my process.php file. I have included this library using composer.
<?php
use Ayesh\InstagramDownload\InstagramDownload;
$url = 'https://www.instagram.com/p/CK9GEIHlcjp/';

try {
  $client = new InstagramDownload($url);
  $url = $client->getDownloadUrl(); // Returns the download URL.
  $type = $client->getType(); // Returns "image" or "video" depending on the media type.
  
}
catch (\InvalidArgumentException $exception) {
  /*
   * \InvalidArgumentException exceptions will be thrown if there is a validation 
   * error in the URL. You might want to break the code flow and report the error 
   * to your form handler at this point.
   */
  $error = $exception->getMessage();
}
catch (\RuntimeException $exception) {
  /*
   * \RuntimeException exceptions will be thrown if the URL could not be 
   * fetched, parsed, or a media could not be extracted from the URL. 
   */
  $error = $exception->getMessage();
}

 echo $url;
 
 echo $error;
 
?>


Please help me out. Thanks in advance

![image](https://user-images.githubusercontent.com/30362030/113508258-9a242a00-956c-11eb-894b-6328a7ce6dbb.png)

**Comment by peter279k** [comment]
@shashifreeze, thanks for your reply.

After I use your codes, I get following result:

```
https://instagram.ftpe7-2.fna.fbcdn.net/v/t51.2885-15/e35/146289388_861563264388633_7251489452048740498_n.jpg?tp=1&_nc_ht=instagram.ftpe7-2.fna.fbcdn.net&_nc_cat=109&_nc_ohc=3tnFd2uRUkAAX_NdcNO&edm=AABBvjUAAAAA&ccb=7-4&oh=2dd76275de75052181ae25c88200712c&oe=608E6245&_nc_sid=83d603&dl=1PHP Notice:  Undefined variable: error in /home/peter/InstagramDownload/error.php on line 33
```

I cannot reproduce your issue.

**Comment by shashifreeze** [comment]
Hi Ayesh, 
thanks for giving time on this, but I have taken the whole snippet from this repo and change only the URL ($url = 'https://www.instagram.com/p/CK9GEIHlcjp/';). 

Please help me with this.  I am an android developer and have very limited knowledge of PHP.

**Comment by peter279k** [comment]
BTW, do you run this PHP program om terminal?

For example, you can use `php getLink.php` rather than using the HTTP method POST via specific URL.

**Comment by Babbar1322** [comment]
Hello 
<br />
<b>Parse error</b>: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in
<b>/home/webcys2/public_html/instaVideoApp/demo/src/InstagramDownload.php</b> on line <b>8</b><br />

this issue is occured on live server ... how to fix 
Thank you

**Comment by Ayesh** [comment]
Hi @Babbar1322 - From the error message, it looks like you are using an older PHP version that this library does not support. Kindly try by updating to PHP 7.4 or PHP 8.0.

**Comment by Babbar1322** [comment]
Hello sir 
i have 7.4.3 php version .. and this code is work for localhost very good but when i try on live server .. this function not return any value.

 public function getDownloadUrl(bool $force_download = true): string {
   
    if (!isset($this->download_url)) {
      $this->process();
    }
    if ($force_download) {
      if (\strpos($this->download_url, '?') !== false) {
        return $this->download_url . '&dl=1';
      }
      return $this->download_url . '?dl=1';
    }
    return $this->download_url;
  }

**Comment by peter279k** [comment]
It will not be worked correctly when publishing on the remote server. But it's worked successfully on the localhost.

I guess that it's not problem for this library and it's about the Instagram server verifying mechanism.

**Comment by Babbar1322** [comment]
what can i do for instagram server verify ??

**Comment by peter279k** [comment]
Please look at this notification description message and it's available on this README:

> Update on May 22, 2020: Due to Instagram no longer allowing anonymous users to view photos/videos, this library is currently not working. A new version 7 is in the works, but there is no ETA yet. Only IGTV videos are working now.

It seems that we should login our Instagram account before fetching the Instagram image with specific Instagram post URL.

And this library doesn't support login Instagram functionality and you can consider other Instagram scrapper for PHP.

Such as [instagram-user-feed](https://github.com/pgrimaud/instagram-user-feed).
