### ISSUE TITLE
Upgrading to the PHPUnit version on branch 5.x

### ISSUE THREAD

**Issue by peter279k** [Ayesh/InstagramDownload#15]
Since the `PHPUnit 9.x` version has been released, I think it should upgrade the PHPUnit version to be good to support `php-7.4` and `php-8.0` versions.

Once this issue has been approved, I can do work on that.

**Comment by Ayesh** [comment]
I think this is a good idea too, preferably to the latest `^9.5.x` series. Thank you.

**Comment by Ayesh** [comment]
Any help is appreciated @peter279k - I think we can release a new 5.1 with PHPUnit 9.5 and other minor changes done. Thank you.
