### ISSUE TITLE
Parse error: syntax error, unexpected 'string' (T_STRING)//src\InstagramDownload.php on line 8

### ISSUE THREAD

**Issue by Najmul-Hasan-Ferdous** [Ayesh/InstagramDownload#17]
What is problem ? I don`t change aything.

**Comment by Ayesh** [comment]
Please make sure you are using the PHP version required from the `composer.json` file.

**Comment by Najmul-Hasan-Ferdous** [comment]
All file are same you provide there

**Comment by Najmul-Hasan-Ferdous** [comment]
I am just inculd index.php and add this line (requred_onece"src\InstagramDownload.php ";)

than got eorr line no 8

**Comment by Ayesh** [comment]
You need to be running PHP versions 7.4 or later. From the error message, it looks like you are using PHP 5.x, that is no longer supported.

**Comment by Ayesh** [comment]
The error message is because your current PHP version is too old for the latest version of this library. 
Please see https://github.com/Ayesh/InstagramDownload/tree/1.0 for an older version that previously supported PHP 5.
