### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Could not fetch data.(//)src\InstagramDownload.php:165 Stack trace: #0

### ISSUE THREAD

**Issue by Najmul-Hasan-Ferdous** [Ayesh/InstagramDownload#18]
What can I do?

**Comment by Ayesh** [comment]
Hi @Najmul-Hasan-Ferdous - This error is when the library could not connect to Instagram. Please see if your server can connect to Instagram. There is also a chance that Instagram has blocked your server IP due to frequent requests.
