### ISSUE TITLE
The obtained pages are the login interface, how to deal with it

### ISSUE THREAD

**Issue by alanyuewei** [Ayesh/InstagramDownload#19]
The obtained pages are the login interface, how to deal with it

**Comment by Ayesh** [comment]
Hi @alanyuewei - Instagram only allows a few posts without logging in. If you get the login interface, it means you have reached this limit. I think it resets every hour.

**Comment by alanyuewei** [comment]
ok, thanks

**Comment by alanyuewei** [comment]
Error fetching information. Perhaps the post is private.
array(6) {
  ["al:ios:app_name"] => string(9) "Instagram"
  ["al:ios:app_store_id"] => string(9) "389801252"
  ["al:ios:url"] => string(40) "instagram://media?id=2548506636504709826"
  ["al:android:app_name"] => string(9) "Instagram"
  ["al:android:package"] => string(21) "com.instagram.android"
  ["al:android:url"] => string(40) "https://www.instagram.com/p/CNeHUiIlrrC/"
}

have not og:video or og:image
