### ISSUE TITLE
Loads and not

### ISSUE THREAD

**Issue by mrcat323** [Ayesh/InstagramDownload#5]
After putting a link to something, it loads the download link, **and don't**, long connection goes. **boring**. fix this please

**Comment by Ayesh** [comment]
Hi, can you provide more information, please? For example the URL to the Instagram post that you are trying to download?

**Comment by Ayesh** [comment]
Hi, just checking...

**Comment by mrcat323** [comment]
I simply grab the link of instagram post and paste it to the script, my internet connection is fine, but with that script it take a long time
