### ISSUE TITLE
use php v 7.2

### ISSUE THREAD

**Issue by Mdhesari** [Ayesh/InstagramDownload#6]
can I use php version 7.2??
I mean does it make any different or issue?

my server does not support higher versions...

**Comment by Ayesh** [comment]
You can use the 3.x version of the library with PHP 7.2. At this time, the 4.x version requires PHP 7.3, but it is technically possible to use it with PHP 7.2, but it's not guaranteed to work. 

You can use the 3.x version with composer:
`composer require ayesh/instagram-download:^3.0.2`

**Comment by Mdhesari** [comment]
I tried last version but it didn't work

So I'm gonna use v 3.x

**Comment by Mdhesari** [comment]
Hi
Sorry for disturbing..

I was able to use of your rep but there is a problem with caption, it's not
complete and it breaks half of it with 3dots....

**Comment by Ayesh** [comment]
Hi @Mdhesari - You are not disturbing at all, and are welcome to post here. 
Could you explain a bit what you mean by 
> breaks half of it with 3dots...

**Comment by Mdhesari** [comment]
Thank you very much for answering

I mean, when a post has long text length it only returns approximately less
than 100 characters and it's limited...

Is there anyway to solve this?

**Comment by Ayesh** [comment]
May I see your code please? This library does not support retrieving the image caption.
